mqtt:
  server: tcp://iot-cloud-k8s:1883
  mode: 0
  downClientId: honeypotDown1
  upClientId: honeypotUp1
  kdd99ClientId: kdd99
honeypot:
  redis:
    addr: 0.0.0.0:6378

  mysql:
    addr: 0.0.0.0:3308
    files: /etc/passwd,/etc/group

  telnet:
    addr: 0.0.0.0:23

  web:
    addr: 0.0.0.0:9000
    template: wordPress/html
    index: index.html
    static: wordPress/static
    url: /