mqtt:
  server: tcp://121.36.70.254:1883
  mode: 0
  downClientId: honeypotDown
  upClientId: honeypotUp
honeypot:
  redis:
    addr: 0.0.0.0:6378

  mysql:
    addr: 0.0.0.0:3308
    files: /etc/passwd,/etc/group