mqtt:
  server: tcp://182.92.222.53:1883
  mode: 0
  downClientId: honeypotDown1
  upClientId: honeypotUp1
honeypot:
  redis:
    addr: 0.0.0.0:6378

  mysql:
    addr: 0.0.0.0:3308
    files: /etc/passwd,/etc/group

  telnet:
    addr: 0.0.0.0:23